### ISSUE TITLE
CPAN Pull Request Challenge

### ISSUE THREAD

**Issue by caipre** [avenj/moox-role-pluggable#1]
Hey @avenj,

I was assigned this project as part of the [CPAN Pull Request Challenge](http://blogs.perl.org/users/neilb/2014/12/take-the-2015-cpan-pull-request-challenge.html). ~~I noticed that there are some files present in the [Meta::CPAN](https://metacpan.org/source/AVENJ/MooX-Role-Pluggable-1.001001) repository that don't seem to be included here (eg, LICENSE). Can you sync up the repositories?~~ Hadn't been introduced to Dist::Zilla yet, ignore this!

Also, are there any issues you'd like to see addressed? Suggestions tend to be fixing any perlcritic or Kwalitee errors; I can help out with those, but bugfixes / new functionality is of course more interesting.

Thanks!

**Comment by avenj** [comment]
Thanks for jumping in!

I suspect perlcritic will never like this codebase very much; dispatch has been micro-optimized into the ground in some ugly ways ;-)

I think perhaps one thing that would help immensely would be the application of a user's critical eye to the documentation. An author's biased viewpoint makes it difficult to critique one's own documentation:  is the software relatively easy to get started with, is the documentation easy to follow and reasonably complete?

I understand if documentation is a bit unappealing ;-) I'll take a gander in the morning and see if any more interesting ideas come to mind.

Thanks again!

**Comment by caipre** [comment]
@avenj : I did a quick pass through the README and made a few minor corrections/changes: https://github.com/caipre/moox-role-pluggable/commit/c5676ae3e0dac959ca9182f12946a485c2b25453 I can submit this as a PR if you'd like.

I noticed that there isn't a method to return the pipeline's ordering; is that something worth having?

**Comment by avenj** [comment]
Good edits, thank you.

The included README.mkdn is actually auto-generated from the module's POD at build-time by Dist::Zilla::Plugin::ReadmeMarkdownFromPod, but I've included those edits in commit f5febb9, along with some other changes that I hope add clarity.

That is a good point regarding pipeline order retrieval. I've tweaked plugin_alias_list to return an ordered list in commit 968b281 (and added a note about the version-dependent behavior).

Appreciate the help! I'm going to close this issue as fixed, but feel free to reopen if I missed anything.

Consider yourself successfully Challenged? ;-)
